fix: correct tekton manifests path in release script
Fix wrong path for tekton tasks manifests in release script.
Move manifests to correct place

Signed-off-by: Karel Šimon <ksimon@redhat.com>

diff --git a/data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml b/data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
--- a/data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
+++ b/data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
@@ -53,7 +53,7 @@ spec:
       default: ""
   steps:
     - name: execute-in-vm
-      image: "quay.io/kubevirt/tekton-task-execute-in-vm:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - entrypoint
       args:
@@ -67,6 +67,8 @@ spec:
         - $(params.command)
         - $(params.args)
       env:
+        - name: COMMAND
+          value: execute-in-vm
         - name: VM_NAME
           value: $(params.vmName)
         - name: VM_NAMESPACE
@@ -155,6 +157,11 @@ spec:
   params:
     - name: manifest
       description: YAML manifest of a VirtualMachine resource to be created.
+      default: ""
+      type: string
+    - name: virtctl
+      description: "Parameters for virtctl create vm command that will be used to create VirtualMachine."
+      default: ""
       type: string
     - name: namespace
       description: Namespace where to create the VM. (defaults to manifest namespace or active namespace)
@@ -168,22 +175,6 @@ spec:
       description: Set runStrategy to VM. If runStrategy is set, vm.spec.running attribute is set to nil.
       default: ""
       type: string
-    - name: dataVolumes
-      description: Add DVs to VM Volumes. Replaces a particular volume if in VOLUME_NAME:DV_NAME format. Eg. ["rootdisk:my-dv", "my-dv2"]
-      default: []
-      type: array
-    - name: ownDataVolumes
-      description: Add DVs to VM Volumes and add VM to DV ownerReferences. These DataVolumes will be deleted once the created VM gets deleted. Replaces a particular volume if in VOLUME_NAME:DV_NAME format. Eg. ["rootdisk:my-dv", "my-dv2"]
-      default: []
-      type: array
-    - name: persistentVolumeClaims
-      description: Add PVCs to VM Volumes. Replaces a particular volume if in VOLUME_NAME:PVC_NAME format. Eg. ["rootdisk:my-pvc", "my-pvc2"]
-      default: []
-      type: array
-    - name: ownPersistentVolumeClaims
-      description: Add PVCs to VM Volumes and add VM to PVC ownerReferences. These PVCs will be deleted once the created VM gets deleted. Replaces a particular volume if in VOLUME_NAME:PVC_NAME format. Eg. ["rootdisk:my-pvc", "my-pvc2"]
-      default: []
-      type: array
   results:
     - name: name
       description: The name of a VM that was created.
@@ -191,24 +182,18 @@ spec:
       description: The namespace of a VM that was created.
   steps:
     - name: createvm
-      image: "quay.io/kubevirt/tekton-task-create-vm:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - create-vm
       args:
         - "--output=yaml"
-        - '--dvs'
-        - $(params.dataVolumes)
-        - '--own-dvs'
-        - $(params.ownDataVolumes)
-        - '--pvcs'
-        - $(params.persistentVolumeClaims)
-        - '--own-pvcs'
-        - $(params.ownPersistentVolumeClaims)
       env:
         - name: VM_MANIFEST
           value: $(params.manifest)
         - name: VM_NAMESPACE
           value: $(params.namespace)
+        - name: VIRTCTL
+          value: $(params.virtctl)
         - name: START_VM
           value: $(params.startVM)
         - name: RUN_STRATEGY
@@ -306,13 +291,15 @@ spec:
       default: ""
   steps:
     - name: run-virt-customize
-      image: "quay.io/kubevirt/tekton-task-disk-virt-customize:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks-disk-virt:v0.15.0"
       command:
         - entrypoint
       args:
         - '--verbose'
         - $(params.verbose)
       env:
+        - name: COMMAND
+          value: disk-virt-customize
         - name: CUSTOMIZE_COMMANDS
           value: $(params.customizeCommands)
         - name: ADDITIONAL_VIRT_CUSTOMIZE_OPTIONS
@@ -432,13 +419,15 @@ spec:
       default: ""
   steps:
     - name: run-virt-sysprep
-      image: "quay.io/kubevirt/tekton-task-disk-virt-sysprep:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks-disk-virt:v0.15.0"
       command:
         - entrypoint
       args:
         - '--verbose'
         - $(params.verbose)
       env:
+        - name: COMMAND
+          value: disk-virt-sysprep
         - name: SYSPREP_COMMANDS
           value: $(params.sysprepCommands)
         - name: ADDITIONAL_VIRT_SYSPREP_OPTIONS
@@ -566,7 +555,7 @@ spec:
       default: ""
   steps:
     - name: execute-in-vm
-      image: "quay.io/kubevirt/tekton-task-execute-in-vm:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - entrypoint
       args:
@@ -574,6 +563,8 @@ spec:
         - $(params.command)
         - $(params.args)
       env:
+        - name: COMMAND
+          value: execute-in-vm
         - name: VM_NAME
           value: $(params.vmName)
         - name: VM_NAMESPACE
@@ -688,12 +679,15 @@ spec:
       description: The namespace of a private key secret.
   steps:
     - name: generate-ssh-keys
-      image: "quay.io/kubevirt/tekton-task-generate-ssh-keys:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - entrypoint
+      args:
         - '--'
         - $(params.privateKeyConnectionOptions)
       env:
+        - name: COMMAND
+          value: generate-ssh-keys
         - name: PUBLIC_KEY_SECRET_NAME
           value: $(params.publicKeySecretName)
         - name: PUBLIC_KEY_SECRET_NAMESPACE
@@ -788,7 +782,7 @@ spec:
       description: The namespace of the data object that was created.
   steps:
     - name: modify-data-object
-      image: "quay.io/kubevirt/tekton-task-modify-data-object:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - modify-data-object
       args:
@@ -879,7 +873,7 @@ spec:
         capabilities:
           drop:
           - "ALL"
-      image: "quay.io/kubevirt/tekton-task-disk-virt-customize:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks-disk-virt:v0.15.0"
       script: |
         #!/bin/bash
         set -x
@@ -890,7 +884,12 @@ spec:
         export TARGET_IMG_FILE_PATH="tmp/target-pvc/disk.img"
 
         guestfish -a ${TARGET_IMG_FILE_PATH} -m /dev/sda tar-out / - | tar xvf - -C ${ISO_FILES_PATH} -m --no-overwrite-dir --owner=$(id -u) --group=$(id -g) --no-same-permissions
- 
+
+        if [ ! -f ${EFI_BOOT}/efisys_noprompt.bin ] || [ ! -f ${EFI_BOOT}/cdboot_noprompt.efi ]; then
+          echo "${EFI_BOOT}/efisys_noprompt.bin or ${EFI_BOOT}/cdboot_noprompt.efi not found in the iso file! Exiting"
+          exit 1
+        fi
+
         chmod u+w "${ISO_FILES_PATH}/efi" "${ISO_FILES_PATH}/efi/microsoft" "${ISO_FILES_PATH}/efi/microsoft/boot"
         chmod u+w "${EFI_BOOT}/efisys.bin" "${EFI_BOOT}/cdboot.efi" "${EFI_BOOT}/efisys_noprompt.bin" "${EFI_BOOT}/cdboot_noprompt.efi"
 
@@ -919,7 +918,7 @@ spec:
         capabilities:
           drop:
           - "ALL"
-      image: "quay.io/kubevirt/tekton-task-modify-data-object:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       script: |
         #!/bin/bash
         set -ex
@@ -946,7 +945,7 @@ spec:
         capabilities:
           drop:
           - "ALL"
-      image: "quay.io/kubevirt/tekton-task-disk-virt-customize:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks-disk-virt:v0.15.0"
       script: |
         #!/bin/bash
         set -x
@@ -998,10 +997,12 @@ spec:
       description: A label selector expression to decide if the VirtualMachineInstance (VMI) is in a failed state. Eg. "status.phase in (Failed, Unknown)". It is evaluated on each VMI update and will result in this task failing if true.
   steps:
     - name: wait-for-vmi-status
-      image: "quay.io/kubevirt/tekton-task-wait-for-vmi-status:v0.14.0"
+      image: "quay.io/kubevirt/tekton-tasks:v0.15.0"
       command:
         - entrypoint
       env:
+        - name: COMMAND
+          value: wait-for-vmi-status
         - name: VMI_NAME
           value: $(params.vmiName)
         - name: VMI_NAMESPACE
